### ISSUE TITLE
0.03 fails since bleadperl v5.19.2-401-g7fa949d

### ISSUE THREAD

**Issue by andk** [ingydotnet/string-slice-pm#3]
Reminds me of https://rt.cpan.org/Ticket/Display.html?id=95093 and https://rt.perl.org/rt3/Ticket/Display.html?id=119295

Does this ring a bell?

**Comment by ingydotnet** [comment]
@andk you rock! Fixed and released.

I'm so bad at keeping track of all this stuff. :\

Please keep the hints coming
